CC=g++

all: task3.o test1.o test2.o test3.o test4.0
	$(CC) -o test_init[] test1.o task3.o
	$(CC) -o test_err[] test2.o task3.o
	$(CC) -o test_oper*= test3.o task3.o
	$(CC) -o test_oper== test4.o task3.o

test1.o:
	$(CC) -c test1.cpp task3.h

test2.o:
	$(CC) -c test2.cpp task3.h

test3.o:
	$(CC) -c test3.cpp task3.h

test4.o:
	$(CC) -c test4.cpp task3.h



test_init[]:
	./test_init[]

test_err[]:
	./test_err[]

test_orep*=:
	./test_oper*=

test_oper==:
	./test_oper==

test: 
	./test_init[]
	./test_err[]
	./test_oper*=
	./test_oper==

clean:
	rm -rf *.o task3